<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

    protected $guarded = [];
    protected $table = 'products';

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    public function orders()
    {
        return $this->belongsToMany(Order::class)->withPivot('qty');
    }

}
